# -*- coding: utf-8 -*-
"""SkinCareProductipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aMrlV_KjZzNoPWa8lvomH9qzkekEGyqG
"""

from google.colab import drive
drive.mount('/content/drive')

# Import required libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier, VotingClassifier, BaggingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder, StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.metrics import classification_report, accuracy_score
from sklearn.utils import resample
from sklearn.pipeline import Pipeline

# Load the dataset
data = pd.read_csv('/content/drive/My Drive/Data.csv')  # Update the dataset path

# Print column names
print("Column Names:", data.columns.tolist())

# Apply describe() on numeric columns
print("\nDataset Description:\n", data.describe())

# Visualize the features
sns.pairplot(data.select_dtypes(include=['float64', 'int64']))
plt.show()

# Handle missing values (categorical and numerical)
# Check for missing values before filling
print("Missing Values Before Filling:\n", data.isnull().sum())

# For numeric features, fill with median
data.fillna(data.median(numeric_only=True), inplace=True)

# For categorical features, fill with mode
data.fillna(data.mode().iloc[0], inplace=True)

# Check missing values again
print("Missing Values After Filling:\n", data.isnull().sum())

# Feature Engineering: Add 'Ingredient Count' and 'Price Bin'
data['Ingredient Count'] = data['Ingredients'].apply(lambda x: len(str(x).split(',')))
data['Price Bin'] = pd.cut(data['Price'], bins=5, labels=False)

# Encode target variable
le_label = LabelEncoder()
data['Label'] = le_label.fit_transform(data['Label'])

# Encode categorical features
le_skin_type = LabelEncoder()
data['Skin Type'] = le_skin_type.fit_transform(data['Skin Type'])

# Define categorical and numerical features
categorical_features = ['Brand', 'Skin Type']
numerical_features = ['Price', 'Rank', 'Ingredient Count', 'Price Bin']

# Preprocessing pipeline
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_features),
        ('cat', OneHotEncoder(handle_unknown='ignore'), categorical_features)
    ]
)

# Split dataset into features (X) and target (y)
X = data[categorical_features + numerical_features]
y = data['Label']

# Balance the dataset using resampling
data_balanced = pd.concat([X, y], axis=1)
majority_class = data_balanced[data_balanced['Label'] == y.value_counts().idxmax()]
minority_classes = [data_balanced[data_balanced['Label'] == label] for label in y.unique() if label != y.value_counts().idxmax()]
resampled_classes = [resample(cls, replace=True, n_samples=len(majority_class), random_state=42) for cls in minority_classes]
data_balanced = pd.concat([majority_class] + resampled_classes)

# Visualize the balanced dataset
sns.countplot(data_balanced['Label'])
plt.title("Balanced Dataset Distribution")
plt.show()

X_balanced = data_balanced[categorical_features + numerical_features]
y_balanced = data_balanced['Label']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_balanced, y_balanced, test_size=0.2, random_state=42)

# Preprocessing pipeline (again, as we split the data)
X_train = preprocessor.fit_transform(X_train)
X_test = preprocessor.transform(X_test)

# Base models
gbm = GradientBoostingClassifier(random_state=42)
rf = RandomForestClassifier(random_state=42)
lr = LogisticRegression(max_iter=1000, random_state=42)  # Increased max_iter for convergence

# Hyperparameter tuning for Random Forest
rf_param_grid = {
    'n_estimators': [100, 200, 300, 400],
    'max_depth': [10, 15, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}
rf_grid_search = GridSearchCV(estimator=rf, param_grid=rf_param_grid, cv=3, n_jobs=-1, verbose=1)
rf_grid_search.fit(X_train, y_train)
rf_best = rf_grid_search.best_estimator_

# Hyperparameter tuning for Gradient Boosting
gbm_param_grid = {
    'n_estimators': [200, 300, 400],
    'learning_rate': [0.01, 0.05, 0.1, 0.2],
    'max_depth': [3, 5, 8]
}
gbm_grid_search = GridSearchCV(estimator=gbm, param_grid=gbm_param_grid, cv=3, n_jobs=-1, verbose=1)
gbm_grid_search.fit(X_train, y_train)
gbm_best = gbm_grid_search.best_estimator_

# Hyperparameter tuning for Logistic Regression
lr_param_grid = {
    'penalty': ['l1', 'l2'],
    'C': [0.5, 1.0, 10.0],
    'solver': ['liblinear']
}
lr_grid_search = GridSearchCV(estimator=lr, param_grid=lr_param_grid, cv=3, n_jobs=-1, verbose=1)
lr_grid_search.fit(X_train, y_train)
lr_best = lr_grid_search.best_estimator_

# Create a Voting Classifier with the best estimators
voting_clf = VotingClassifier(estimators=[('gbm', gbm_best), ('rf', rf_best), ('lr', lr_best)], voting='soft')
voting_clf.fit(X_train, y_train)

# Wrap VotingClassifier in BaggingClassifier
bagging_clf = BaggingClassifier(estimator=voting_clf, n_estimators=50, random_state=42)
bagging_clf.fit(X_train, y_train)

# Evaluate the BaggingClassifier
y_train_pred = bagging_clf.predict(X_train)
y_test_pred = bagging_clf.predict(X_test)

# Print accuracy scores
print("Training Accuracy with Bagging:", accuracy_score(y_train, y_train_pred))
print("Testing Accuracy with Bagging:", accuracy_score(y_test, y_test_pred))

# Display classification reports
print("\nTraining Classification Report with Bagging:")
print(classification_report(y_train, y_train_pred))
print("\nTesting Classification Report with Bagging:")
print(classification_report(y_test, y_test_pred))

# Function to display recommended products
def recommend_products_bagging(skin_type_input):
    try:
        # Encode user input
        encoded_skin_type = le_skin_type.transform([skin_type_input])[0]

        # Filter data for the user's skin type
        filtered_data = data[data['Skin Type'] == encoded_skin_type]

        # Recommend products for each label category
        recommendations = {}
        for label in le_label.classes_:
            encoded_label = le_label.transform([label])[0]
            products = filtered_data[filtered_data['Label'] == encoded_label][['Name', 'Price']].head(2)
            recommendations[label] = products.values.tolist()

        # Prepare output
        output = f"Recommendations for {skin_type_input} skin:\n"
        for label, items in recommendations.items():
            output += f"  {label}:\n"
            for i, (name, price) in enumerate(items, start=1):
                output += f"    {i}. {name}: ${price}\n"
        return output

    except ValueError:
        return "Invalid Skin Type! Please ensure input matches dataset values."

# User interaction for Bagging-based recommendations
while True:
    print("\n--- Product Recommendation System (Bagging Model) ---")
    user_skin_type = input("Enter Skin Type (e.g., Dry, Oily, Sensitive, Normal or 'exit' to quit): ")
    if user_skin_type.lower() == "exit":
        break
    result = recommend_products_bagging(user_skin_type)
    print(result)